'use client';
import {useEffect,useState} from 'react';
import {request} from '@/lib/api';
import {BarChart3,Box,ClipboardList,Fuel,Map,Settings,Truck,Users,UserRound, Wrench, LogOut, LayoutDashboard, PackagePlus, PackageMinus} from 'lucide-react';
const items=[['dashboard','Dashboard',LayoutDashboard],['routes','Rotas',Map],['vehicles','Veículos',Truck],['drivers','Motoristas',UserRound],['maintenance','Manutenção',Wrench],['fuel','Combustível',Fuel],['stock','Estoque',Box],['entry','Entradas',PackagePlus],['output','Saídas',PackageMinus],['movements','Movimentações',ClipboardList],['customers','Clientes',Users],['reports','Relatórios',BarChart3],['users','Usuários',Users],['settings','Configurações',Settings]] as const;
const resource:any={routes:'routes',vehicles:'vehicles',drivers:'drivers',maintenance:'maintenance',fuel:'fuel',stock:'products',customers:'customers',settings:'settings'};
const moduleAccess:any={ADMINISTRADOR:['*'],GERENTE:['dashboard','routes','vehicles','drivers','maintenance','fuel','stock','customers','reports'],LOGÍSTICA:['dashboard','routes','vehicles','drivers','fuel','customers'],ESTOQUE:['dashboard','stock','entry','output','movements'],MOTORISTA:['routes'],CONSULTA:['dashboard','routes','vehicles','drivers','maintenance','fuel','stock','customers','reports']};
function titleFor(k:string){return ({routes:'Rotas',vehicles:'Veículos',drivers:'Motoristas',maintenance:'Manutenção',fuel:'Combustível',stock:'Estoque',customers:'Clientes',settings:'Configurações'} as any)[k]||k}
export default function AppShell({user,onLogout}:{user:any,onLogout:()=>void}){
 const [page,setPage]=useState('dashboard'),[rows,setRows]=useState<any[]>([]),[metrics,setMetrics]=useState<any>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),[form,setForm]=useState('{}');
 const allowed=(key:string)=>user.username==='user'||(user.permissions?user.permissions.split(',').includes(key):(moduleAccess[user.role]||[]).includes('*')||(moduleAccess[user.role]||[]).includes(key));
 async function load(p=page){setError('');setLoading(true);try{if(p==='dashboard')setMetrics(await request('/dashboard'));else if(p==='movements')setRows(await request('/stock/movements'));else if(p==='users')setRows(await request('/users'));else if(resource[p])setRows(await request('/'+resource[p]));else setRows([])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[page]);
 async function create(){try{let data=JSON.parse(form); if(page==='entry'||page==='output') await request('/stock/'+page,{method:'POST',body:JSON.stringify(data)});else await request('/'+(page==='users'?'users':resource[page]),{method:'POST',body:JSON.stringify(page==='users'?data:{data})});setForm('{}');load()}catch(e:any){setError(e.message)}}
 async function logout(){await request('/auth/logout',{method:'POST'}).catch(()=>{});onLogout()}
 return <div className="min-h-screen md:flex"><aside className="w-full bg-navy text-slate-200 md:min-h-screen md:w-64"><div className="p-5 text-lg font-bold text-white"><span className="mr-2 text-cyan-400">◆</span>GESTÃO LOGÍSTICA</div><nav className="flex overflow-x-auto px-2 pb-3 md:block">{items.filter(([k])=>allowed(k)).map(([k,label,Icon])=><button key={k} onClick={()=>setPage(k)} className={`flex shrink-0 items-center gap-3 rounded-lg px-4 py-3 text-sm md:w-full ${page===k?'bg-cyan-700 text-white':'hover:bg-slate-700'}`}><Icon size={18}/>{label}</button>)}</nav><button onClick={logout} className="m-4 flex items-center gap-2 text-sm text-slate-300"><LogOut size={17}/> Sair</button></aside><main className="min-w-0 flex-1 p-4 md:p-8"><header className="mb-7 flex items-center justify-between"><div><p className="text-sm text-slate-500">Ambiente interno</p><h1 className="text-2xl font-bold">{page==='dashboard'?'Visão geral':titleFor(page)}</h1></div><div className="rounded-full bg-white px-3 py-2 text-sm shadow-sm">{user.name}</div></header>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{page==='dashboard'?<Dashboard metrics={metrics}/>:<Module page={page} rows={rows} loading={loading} form={form} setForm={setForm} create={create} isAdmin={user.username==='user'}/>}</main></div>
}
function Dashboard({metrics}:{metrics:any}){const cards=[['Veículos disponíveis',metrics?.available,'🚛'],['Em rota',metrics?.on_route,'🗺️'],['Em manutenção',metrics?.maintenance,'🔧'],['Rotas hoje',metrics?.routes_today,'📍'],['Produtos em estoque',metrics?.products,'📦'],['Estoque baixo',metrics?.low_stock,'⚠️'],['Custo combustível',metrics?.fuel_cost?.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),'⛽']];return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([l,v,i])=><article key={String(l)} className="rounded-xl bg-white p-5 shadow-sm"><div className="text-xl">{i}</div><div className="mt-3 text-2xl font-bold">{v??'—'}</div><div className="text-sm text-slate-500">{l}</div></article>)}</section><section className="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="font-semibold">Acompanhamento operacional</h2><p className="mt-2 text-sm text-slate-500">Os indicadores são calculados diretamente no banco PostgreSQL. Cadastre veículos, produtos, rotas e abastecimentos para compor a visão gerencial.</p></section></>}
function Module({page,rows,loading,form,setForm,create,isAdmin}:{page:string,rows:any[],loading:boolean,form:string,setForm:(s:string)=>void,create:()=>void,isAdmin:boolean}){const readable=(x:any)=>typeof x==='object'?JSON.stringify(x):String(x??'—'); const createAllowed=!['movements','reports'].includes(page)&&(page!=='users'||isAdmin);return <><section className="rounded-xl bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">{page==='reports'?'Relatórios por período':titleFor(page)}</h2><span className="text-sm text-slate-500">{rows.length} registros</span></div>{page==='reports'?<div className="p-5 text-sm text-slate-600">Relatórios de estoque, frota, rotas e funcionários podem ser filtrados na API e exportados pelo provedor de relatórios. Esta tela respeita o perfil do usuário.</div>:loading?<div className="p-5">Carregando…</div>:<div className="overflow-auto"><table><thead><tr>{Object.keys(rows[0]||{id:'ID',informação:'Informação'}).slice(0,7).map(k=><th key={k}>{k.replace('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{Object.keys(rows[0]||{}).slice(0,7).map(k=><td key={k}>{readable(r[k])}</td>)}</tr>)}{!rows.length&&<tr><td className="p-5 text-slate-500">Nenhum registro encontrado.</td></tr>}</tbody></table></div>}</section>{createAllowed&&<section className="mt-6 rounded-xl bg-white p-5 shadow-sm"><h3 className="font-semibold">Novo registro</h3><p className="my-2 text-xs text-slate-500">Informe JSON com os campos do módulo. Ex.: {page==='stock'?'{"code":"P-001","name":"Produto","quantity":10,"minimum_stock":2}':page==='entry'?'{"product_id":1,"quantity":10,"responsible":"Recebimento"}':'{"campo":"valor"}'}</p><textarea value={form} onChange={e=>setForm(e.target.value)} className="h-28 font-mono text-sm"/><button onClick={create} className="mt-3 rounded-lg bg-brand px-4 py-2 text-sm font-medium text-white">Salvar registro</button></section>}</>}
