"""remove the commercial module and its persisted data

Revision ID: 0003_remove_commercial
Revises: 0002_audit_details
"""
from alembic import op

revision = "0003_remove_commercial"
down_revision = "0002_audit_details"
branch_labels = None
depends_on = None


def upgrade():
    # A remoção é intencional e permanente: faça backup antes de aplicar.
    # O banco pode conter tanto o cadastro antigo de produtos quanto o fluxo
    # legado de pedidos comerciais. Todos pertencem ao módulo removido.
    op.execute(
        "DROP TABLE IF EXISTS public.commercial_order_items, "
        "public.commercial_orders, public.commercial_products CASCADE"
    )

    # O modelo atual usa unicidade de placa por unidade. Corrige bancos que
    # ainda possuem o índice global criado pelo schema inicial.
    op.execute("DROP INDEX IF EXISTS ix_vehicles_plate")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_vehicles_org_unit_plate'
            ) THEN
                ALTER TABLE vehicles
                ADD CONSTRAINT uq_vehicles_org_unit_plate UNIQUE (org_unit, plate);
            END IF;
        END $$;
        """
    )


def downgrade():
    op.execute(
        "ALTER TABLE vehicles DROP CONSTRAINT IF EXISTS uq_vehicles_org_unit_plate"
    )
    op.create_index("ix_vehicles_plate", "vehicles", ["plate"], unique=True)
    # O downgrade não recria dados comerciais, apenas a tabela vazia.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS commercial_products (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            org_unit VARCHAR(20) NOT NULL DEFAULT 'matriz',
            code VARCHAR(60),
            name VARCHAR(160) NOT NULL,
            price NUMERIC(12, 2) NOT NULL,
            unit VARCHAR(20),
            category VARCHAR(80),
            notes TEXT,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
        )
        """
    )
